.vscode/settings.json
README.md
config/webpack.config.js
package.json
scripts/serve.js
src/App.tsx
src/index.tsx
src/services/authService.ts
src/services/types.ts
src/stores/AuthStore.tsx
src/stores/RootStore.tsx
src/stores/UserStore.tsx
src/stores/stores.tsx
src/tsconfig.json
yarn.lock

Basic scaffolding for mobx, context, and service layers + hot reloading

Scaffolding

---

.gitignore
package.json
server/app.py
server/fake.py
src/App.tsx
src/components/PatientDetail/AssessmentProgress.tsx
src/components/PatientDetail/PatientDetailPage.tsx
src/components/PatientDetail/ProgressInformation.tsx
src/components/PatientDetail/SessionInfo.tsx
src/components/caseload/CaseloadPage.tsx
src/components/caseload/CaseloadTable.tsx
src/components/chrome/HeaderContent.tsx
src/components/common/Page.tsx
src/services/enums.ts
src/services/registryService.ts
src/services/types.ts
src/stores/PatientStore.tsx
src/stores/RootStore.tsx
src/styles/theme.ts
src/utils/assessment.ts
src/utils/time.ts
yarn.lock

Updated changes to latest design with different table prototypes (X-Grid)

Patientinfo

---

scope_shared/scope/database/collection_utils.py
scope_shared/scope/database/patients.py
scope_shared/scope/testing/fake_data/fake_utils.py
scope_shared/scope/testing/fake_data/fixtures_fake_case_review.py
scope_shared/scope/testing/fake_data/fixtures_fake_identity.py
scope_shared/scope/testing/fake_data/fixtures_fake_session.py
scope_shared/scope/testing/test_schemas/json/patient.json

Moved ID generation function into collection_utils

---

web_patient/src/components/Forms/SafetyPlanForm.tsx
web_registry/src/components/PatientDetail/MoodProgress.tsx
web_registry/src/components/caseload/CaseloadPage.tsx
web_registry/src/components/common/SessionProgressVis.tsx
web_registry/src/stores/PatientsStore.ts
web_shared/enums.ts

- remove daily option for assessment config
- set auth tokens for patient first load
- mood logging panel reactive
- independent observables for safety plan data
- min date range for session vis

Variety of fixes

---

server_flask/app_config/assessments/medication.json
web_patient/src/components/Forms/FormSection.tsx
web_patient/src/services/strings.ts
web_patient/src/styles/theme.ts

Reduced header text a tad
Increased subheader text size and bolded it

Updated patient app form styling + tab/page name changes

---

scope_shared/scope/enums.py
scope_shared/scope/schemas/enums.json
scope_shared/scope/schemas/patient-profile.json
web_registry/src/components/PatientDetail/PatientProfileDialog.tsx
web_registry/src/components/caseload/CaseloadTable.tsx
web_shared/enums.ts
web_shared/types.ts

- added site menu drop down in patient profile
- added site column to caseload table

Add 5 sites to profile

---

web_registry/src/components/PatientDetail/AssessmentProgress.tsx

Note that I didn't change totalScore. It is still -1. Wasn't sure if that value is used for some validation. If not, we should make that value blank as well by default.

Updated total score default for assessments to blank instead of -1

---

web_registry/src/utils/assessment.ts

Sort IAssessmentContent using id

---

web_patient/src/components/Chrome/Login.tsx
web_registry/src/components/chrome/Login.tsx

- Toggle to show password and retype password #280

Toggle to show password and retype password

---

web_patient/src/services/strings.ts

Update Text in Safety Plan Subtitle

---

web_patient/src/components/Forms/ActivityLoggingForm.tsx
web_patient/src/components/Progress/ActivityTrackingHome.tsx
web_patient/src/components/Progress/AssessmentHome.tsx
web_patient/src/components/Progress/MoodTrackingHome.tsx
web_patient/src/components/common/Table.tsx
web_patient/src/services/strings.ts
web_registry/src/components/PatientDetail/ActivityProgress.tsx
web_registry/src/components/PatientDetail/AssessmentProgress.tsx
web_registry/src/components/PatientDetail/MoodProgress.tsx
web_registry/src/components/PatientDetail/SessionReviewTable.tsx
web_registry/src/components/common/Table.tsx
web_registry/src/services/strings.ts

- Fix activity tracking detail in registry and patient app #288 #287 
- Rename Values Inventory to Values & Activities Inventory #300
- Widen recommendation column in registry session table #298
- Allow multiline comment in tables #297

Fixes to registry tables, activity tracking, and values inventory title

---

web_shared/enums.ts

This frequency is actually defined as `Every 4 weeks`.
Fixes #326.

Fix "Monthly" Assessment Frequency

---

scope_shared/scope/schema.py
scope_shared/scope/schemas/document.json
scope_shared/scope/testing/test_schemas/test_fake_data_schemas.py

Notes to discuss with James:
* In test_fake_data_schemas.py, expected_document flag for contact and referral-status

Introduce Document Schema

---

web_patient/src/components/Forms/AssessmentForm.tsx
web_patient/src/components/Resources/CrisisResourcesPage.tsx

Updated per issue #330 and for textual consistency.

Update Crisis Help Resources

---

scope_shared/scope/tasks/database_reset.py

Database Reset Path Fix

---

web_patient/src/services/strings.ts
web_registry/src/services/strings.ts

Corrected to "Values & Activities Inventory".
Fixes #315.

Fix references to "Values Inventory"

---

scope_shared/scope/schemas/documents/activity.json
scope_shared/scope/schemas/documents/utils/life-area-value.json
scope_shared/scope/schemas/utils/enums.json
scope_shared/scope/testing/test_schemas/json/patient.json
scope_shared/scope/testing/test_schemas/json/values-inventory.json

Create and use a schema enum for `lifeareaId`.

Create Schema Enum for lifeareaId

---

web_patient/src/components/Forms/ActivityLoggingForm.tsx

Disabled next button if success is empty:

Client Activity Logging Fix

---

web_patient/src/components/Forms/AddEditActivityForm.tsx

| ![before](https://github.com/uwscope/scope-web/assets/2163573/0033883e-c5c3-4895-88ac-e7267c6fa0a7) | ![Screenshot 2023-06-26 at 12-59-25 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/5801d03f-9ab9-4eab-9ea2-4b12277d496f) |

Display Activity Name when Scheduling Activity

---

web_patient/src/components/ValuesInventory/LifeAreaDetail.tsx
web_patient/src/services/strings.ts

With no existing values in a life area:
| ![Screenshot 2023-06-26 at 08-39-23 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/879e22e4-cb87-4698-bb84-fcc933b50daa) | ![Screenshot 2023-06-26 at 08-32-11 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/068d4cd4-2cc6-4c99-bd86-b1e772b59de5) |
With existing values in a life area, top of scroll:
| ![before_top_of_scroll](https://github.com/uwscope/scope-web/assets/2163573/7a9a1585-2c3e-4323-a515-9ea4fef73d81) | ![after_top_of_scroll](https://github.com/uwscope/scope-web/assets/2163573/f38ec8c1-4f3b-4241-8eb5-d65ebf8aadb4) |
With existing values in a life area, bottom of scroll:
| …

Provide Sample Activities in Values & Activities Inventory

---

web_patient/src/components/Progress/ActivityTrackingHome.tsx
web_patient/src/components/Progress/AssessmentHome.tsx
web_patient/src/components/Progress/MoodTrackingHome.tsx

Includes Depression, Anxiety, Activity, & Mood Logs.
| ![activities_before](https://github.com/uwscope/scope-web/assets/2163573/f471bdae-f33d-4726-a2ba-bfc6c5b4b8cf) | ![activities_after](https://github.com/uwscope/scope-web/assets/2163573/18b49426-3465-4afb-aaaa-0659fe9ca20c) |

Reverse Chronological Sorting of Logs in Progress Tab

---

web_registry/src/components/PatientDetail/PatientProfileDialog.tsx
web_shared/sorting.ts

When rendered in Patient Information dropdown:
| ![sort_before](https://github.com/uwscope/scope-web/assets/2163573/adcc933b-e074-4096-8e66-be55439637bc) | ![sort_after](https://github.com/uwscope/scope-web/assets/2163573/f2b819c2-b0be-4cbe-a378-ace2a4e1e0b3) |

Sort Social Workers by Name

---

web_registry/src/stores/PatientsStore.ts

| ![caseload_before](https://github.com/uwscope/scope-web/assets/2163573/133bb8fb-b175-41a6-b760-a1c17c4d10b3) | ![caseload_after](https://github.com/uwscope/scope-web/assets/2163573/585e3ec6-3ae5-403f-96e6-b192f0ab4f74) |

Sort Social Workers in Caseload Filter

---

web_patient/src/components/Resources/AboutUsPage.tsx

Jesse requested we change ‘Seattle Cancer Alliance’ to ‘Fred Hutchinson Cancer Center.’ 
| ![Screenshot 2023-08-21 at 08-07-02 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/24e019ff-c184-4d02-8d02-d2565c212543) | ![Screenshot 2023-08-21 at 08-08-06 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/fdaaf2a8-f8a0-4380-8e50-e3355111170b) |

AboutUsPage Update

---

scope_shared/scope/enums.py
scope_shared/scope/schemas/utils/enums.json
server_flask/enums.py
web_shared/enums.ts

Add "No show" as a Registry Session Type
| ![453_before](https://github.com/uwscope/scope-web/assets/2163573/466a67f3-d6ff-4b49-b66c-834ab2d556c7) | ![453_after](https://github.com/uwscope/scope-web/assets/2163573/d4c70b7e-7189-4a10-8741-d187afb9a505) |

Add "No show" as a Session Type in Registry

---

web_registry/src/components/caseload/CaseloadTable.tsx

Fixes #281, using highlighting logic described there.

Highlight Overdue Case Review

---

web_registry/src/components/caseload/CaseloadTable.tsx

Fixes a UTC date bug introduced in #474.

Fix for UTC Date Comparison in Review Review Overdue Calculation

---

web_registry/src/components/PatientDetail/ProgressInformation.tsx

Commit was accidentally missing in #500

Missing Commit in Mood Log Pull Request

---

web_registry/src/components/PatientDetail/TreatmentInfo.tsx

Fix Compile Error

---

web_registry/src/components/PatientDetail/PatientInformation.tsx
web_registry/src/components/PatientDetail/RecentInteraction.tsx
web_registry/src/stores/PatientStore.ts

Working toward #511.
- Adds a basic `mostRecentPatientInteractionDate`.
- Starts to define `recent` properties as filters on patient data.
- Introduces a `RecentInteraction` component for debugging.

Begin to Stub Indicators of Recent Patient Interaction

---

web_patient/src/components/Resources/HowToVideosPage.tsx

The team made vertical versions of the app introductory videos.  This updates to us those new videos.

Update Patient App Videos to Vertical Format

---

web_registry/src/components/PatientDetail/ActivityProgress.tsx
web_registry/src/components/PatientDetail/AssessmentProgress.tsx
web_registry/src/components/PatientDetail/MoodProgress.tsx
web_registry/src/components/PatientDetail/PatientDetailPage.tsx
web_registry/src/components/common/Table.tsx
web_registry/src/stores/PatientStore.ts

Enhance patient details page with recent entry badges in the "Contents" and with corresponding row highlights.

Enhance Patient Details Page with Recent Entry Badges and Row Highlights

---

web_registry/src/stores/PatientStore.ts

`New` badge is displayed, 
but nothing comes up in patient detail:

Remove Recent Scheduled Activities from Caseload Summary Calculation

---

web_registry/src/stores/PatientStore.ts

This is a follow-up to #525, simply improving documentation of the associated code.

Improved Documentation of Recent Entry Summary
