uwscope/scope-web

- scope_shared/scope/database/patients.py
- scope_shared/scope/populate/patient/populate_default_data.py
Fixes #268:
- Safety plan no longer assigned by default.
- Values inventory no longer assigned by default.
- GAD7 no longer assigned by default.
- PHQ9 no longer assigned by default.
Relevant:
- Medication tracking was already not assigned by default, continues to not be assigned by default.
> Change Default Assignments in New Patient Population

- web_registry/src/components/PatientDetail/AssessmentProgress.tsx
- web_registry/src/stores/PatientStore.ts
- Registry app: Send date time of click interaction as `assignedDateTime` in assessments #270
> Fixed assignedDateTime in assessments

- Pipfile.lock
- scope_shared/scope/populate/data/rule_export_archive.py
- scope_shared/scope/populate/data/rule_export_database.py
- scope_shared/scope/populate/populate.py
- scope_shared/scope/schema.py
- scope_shared/scope/schemas/populate/populate-config.json
- scope_shared/setup.py
- secrets/data/.gitignore
- server_celery/Pipfile.lock
- server_flask/Pipfile.lock
Add support for export of an encrypted database archive.
- Incidental updates to dependencies
- Incidental improvement in error messaging when schemas fail to parse at startup
> Support Export of Encrypted Database Archive

- scope_shared/scope/schema_utils.py
- scope_shared/scope/schemas/documents/activity-log.json
- scope_shared/scope/testing/fake_data/fake_utils.py
- scope_shared/scope/testing/fake_data/fixtures_fake_activity_logs.py
- scope_shared/scope/testing/test_schemas/json/activity-log/no-success-disallows-accomplishment-and-pleasure-valid.json
- scope_shared/scope/testing/test_schemas/json/activity-log/no-success-disallows-accomplishment-invalid.json
- scope_shared/scope/testing/test_schemas/json/activity-log/no-success-disallows-pleasure-invalid.json
- scope_shared/scope/testing/test_schemas/test_json_schemas.py
#308 fixed #288, but did not include a corresponding schema update because we could not detect / fix any pre-existing documents that might conflict with schema update. Now that we can detect pre-existing documents that conflict with a schema, this updates the activity-log schema for the same reasons we made client updates in #308.
Fixes #317.
> Add Schema Checks for Activity Logs

- web_patient/src/services/appService.ts
- web_patient/src/services/configService.ts
- web_registry/src/services/configService.ts
- web_shared/serviceBase.ts
Our current implementation of `/patient` and `/patients` involves many database roundtrips for each patient, so the delay becomes unworkable when Flask is running locally. This dramatically extends the client timeout as a workaround.
This is not yet a critical issue in production, but will need to be fixed there as our number of patients continues to grow.
> Set Extremely Long Client Timeouts

- web_registry/src/components/caseload/CaseloadTable.tsx
This uses the existing `renderHeader` to hack some space out of date columns, allowing us to make the name column wider.
Before and after screenshots below:
- Dates still fit.
- Overall width is not any greater.
It would be better to do this by forcing certain line wraps, continuing to use `minWidth`. But this hacks it in for now.
> Adjust Columns to Create More Space for Patient Name

- web_patient/src/services/strings.ts
> We forgot to update the ‘Suicide Prevention Lifeline phone’. Would update to ‘Suicide & Crisis Lifeline’ and add ‘988 or 1-800-…’
> Safety Plan String Update

- web_patient/src/components/Forms/FormDialog.tsx
- web_patient/src/components/Forms/MoodLoggingForm.tsx
- web_patient/src/components/Resources/CrisisResourcesPage.tsx
- web_patient/src/services/strings.ts
Adds text to the mood logging screen clarifying it may not be reviewed right away:
| ![mood_checkin_before](https://github.com/uwscope/scope-web/assets/2163573/fc26b5e4-104c-4b10-9bcb-64440fa18172) | ![Screenshot 2023-06-26 at 12-34-56 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/c93221cb-bd33-492b-a570-ecd2767f1b4e) |
Adds a link to crisis resources in the follow-up toast:
| ![toast_before](https://github.com/uwscope/scope-web/assets/2163573/a46ba5c4-cde0-45ed-9a00-6c5650e97812) | ![Screenshot 2023-06-26 at 12-35-18 SCOPE App](https://github.com/uwscope/scope-web/assets/2163573/0abc8b8c-ddc8-411d-8b62-1ca91ff9e811) |
Fixes #398
> Update Mood Logging for Crisis Resources

- web_patient/src/components/Forms/MoodLoggingForm.tsx
Robustness fix for #430.
Existing code works fine, but coincidentally because the included link was from a page at the root. Making the leading slash explicit to help with future copy-paste.
> Robustness Fix for #430

- server_flask/app_config/patient_resources/3bamodel.json
- web_patient/src/components/ValuesInventory/ValuesInventoryHome.tsx
- web_patient/src/services/strings.ts
Added requested link to Activity Ideas in Values & Activities Inventory:
| ![before_inventory](https://github.com/uwscope/scope-web/assets/2163573/59cd7240-74e9-4732-80bf-362415e56576) | ![after_inventory](https://github.com/uwscope/scope-web/assets/2163573/01afe3b2-f3d8-4fc0-8945-3a3090532d25) |
Renamed "Activity Menu" to "Activity Ideas" because of confusion when describing it from anywhere else:
| ![before_library](https://github.com/uwscope/scope-web/assets/2163573/6b5e6818-d352-4192-bc07-358f67a03f64) | ![after_library](https://github.com/uwscope/scope-web/assets/2163573/a7e4504d-afdf-4203-95b3-67867385d371) |
> Update Values Inventory with Link to Activity Ideas

- web_registry/src/components/PatientDetail/SessionInfo.tsx
- web_registry/src/components/PatientDetail/SessionReviewTable.tsx
Session Information Changed from "Medication Changes" to "Medication Notes":
| ![session_before](https://github.com/uwscope/scope-web/assets/2163573/73258409-d0e6-4719-adf2-998fac9212b5) | ![session_after](https://github.com/uwscope/scope-web/assets/2163573/d8225906-4505-4a39-b957-a1d909788fe5) |
Case Review Remains "Medication Changes":
| ![review_before](https://github.com/uwscope/scope-web/assets/2163573/daafcfb7-36d6-4468-8bbd-a118a63fd9a5) | ![review_after](https://github.com/uwscope/scope-web/assets/2163573/6f516d96-9d98-49e6-bdf3-f40814b52332) |
Table Changed from "Med Changes" to "Med Changes / Notes":
| ![table_before](https://github.com/uwscope/scope-web/assets/2163573/d …
> Updated Titles for Medication "Changes" versus "Notes"

- tasks/web_patient.py
Fix port number in instructions for `invoke prod.patient.serve`.
> Update Invoke Task Documentation

- web_patient/src/components/Chrome/Login.tsx
- web_registry/src/components/chrome/Login.tsx
Adds error handling around password creation and entry.
Accidental spaces when copy-pasting passwords were causing login failures. Passwords are now automatically trimmed during both creation and entry. Entry continues to allow an interior space as part of a password, but creation now does not.
Password creation now gives minimal feedback on password criteria.
> Add Error Handling in Password Entry and Creation

- web_patient/src/components/Forms/AddEditActivityForm.tsx
- web_patient/src/components/ValuesInventory/LifeAreaDetail.tsx
- web_patient/src/services/strings.ts
It was possible to accidentally create two values in the same area with the same name.
This adds testing for uniqueness at the time of value name creation / editing.
This also ensure value names are trimmed upon creation / editing.
| <img width="200" alt="image" src="https://user-images.githubusercontent.com/1428399/227382860-ea228bcf-1657-4d29-b36e-7f021388b395.png">| <img width="150" alt="image" src="https://github.com/uwscope/scope-web/assets/2163573/48bd2357-bbf2-4c8a-959f-4698cf348d9a"> <img width="150" alt="image" src="https://github.com/uwscope/scope-web/assets/2163573/82273505-0487-4ab9-9420-129ad09e533b"> <img width="150" alt="image" src="https://github.com/uwscope/scope-web/assets/2163573/9a092085-65c3-411c-8812-65753cc56885">|
> Ensure Uniqueness of Created/Edited Value Names

- web_registry/src/components/PatientDetail/AssessmentProgress.tsx
- web_registry/src/components/PatientDetail/MedicationProgress.tsx
- web_registry/src/components/PatientDetail/SafetyPlan.tsx
- web_registry/src/components/PatientDetail/ValuesInventory.tsx
- web_registry/src/services/strings.ts
In discussion of #417, we decided to go with "Cancel Assignment".
We also decided the [ContentPasteOff](https://mui.com/material-ui/material-icons/?query=contentpas&selected=ContentPasteOff) icon would work well.
In making that change, found that the default "Filled" version of the icon is not filled. It is identical to "Outlined". The result looked bad next to other icons which are "Filled", so I adjusted all of them to "Outlined".
Assign / Cancel Assignment:
Assign / Reassign:
> Update Cancel Assignment Text and Icons

- web_registry/src/components/PatientDetail/BAChecklist.tsx
- web_registry/src/components/PatientDetail/PatientCardExtended.tsx
- web_registry/src/components/PatientDetail/SessionInfo.tsx
- web_registry/src/components/PatientDetail/TreatmentInfo.tsx
- web_registry/src/components/caseload/CaseloadTable.tsx
- web_registry/src/stores/PatientStore.ts
- web_shared/sorting.ts
The underlying order of sessions objects has been based on `_id`, which in turn corresponds to the order in which documents were added to the database. This often appears to also be sorted by date, but that correlation breaks down if a session is edited. A new document will be created for the edit, which will appear most recent regardless of its underlying date.
This was showing up as several weird behaviors:
- Incorrect and even negative values in the Caseload:
- Incorrect dates in the patient summary:
- Incorrect dates and potentially incorrect data in treatment summary:
This update fixes all of these issues, consistently sorting sessions by date before using them.
> Consistently Sort Sessions by Date

- web_registry/src/components/PatientDetail/SessionInfo.tsx
- web_registry/src/components/caseload/CaseloadTable.tsx
- web_registry/src/stores/PatientStore.ts
- web_shared/sorting.ts
Similar to #479, case reviews have been defaulted sorted by `_id`. This often appears correct, but may not be correct if a case review is edited or otherwise entered in a non-chronological order.
For a pair of case reviews:
It was possible for the "Last Case Review" to be incorrect:
This update introduces and consistently uses utilities for sorting case reviews by date.
> Consistently Sort Case Reviews by Date

- .editorconfig
With black and prettier now formatting our code, a simple `.editorconfig` would be consistent.
Resolves #3.
> Create an .editorconfig

- web_patient/src/components/Chrome/AppHost.tsx
- web_patient/src/components/Chrome/Login.tsx
- web_patient/src/services/strings.ts
- web_registry/src/components/chrome/AppHost.tsx
- web_registry/src/components/chrome/HeaderContent.tsx
- web_registry/src/components/chrome/Login.tsx
- web_shared/authStoreBase.ts
Implement password resets via emailed code, together with server updates in:
https://github.com/uwscope/scope-aws-infrastructure/pull/30
Adds a "Forgot Password?" prompt at login, which toggle a reset request form:
| | Registry | App |
| - | - | - |
| Login | <img width=250 src="https://github.com/uwscope/scope-web/assets/2163573/6ac98910-3b72-4cca-bb2f-ae49d83f6f40"/> | <img width=250 src="https://github.com/uwscope/scope-web/assets/2163573/ed2aac6c-926d-48b6-ac4b-c5c4bb6ccb7d" /> <tr></tr> |
| Reset Request | <img width=250 src="https://github.com/uwscope/scope-web/assets/2163573/58e7c893-db98-4172-8b80-6449c689d7fb"/> | <img width=250 src="https://github.com/uwscope/scope-web/assets/2163573/d0c5b014-d938-4ac1-bafe-aedd63f05f15" /> <tr></tr> |
Request generates an email:
This code and a …
> Enable Password Reset Using Cognito-Emailed Code

- web_patient/src/components/Chrome/Login.tsx
- web_registry/src/components/chrome/Login.tsx
Improved error message for password attempt limit.
This condition was not explicitly handled.
> Improved Error Message for Password Attempt Limit

- web_registry/src/components/PatientDetail/AssessmentProgress.tsx
- web_registry/src/components/PatientDetail/ProgressInformation.tsx
- web_registry/src/components/PatientDetail/TreatmentInfo.tsx
- web_registry/src/stores/PatientStore.ts
- web_shared/sorting.ts
Utility functions for sorted assessment logs.
Existing uses of the unsorted assessment logs appear to have been correct.
Not all uses of `patientStore.assessments` have been replaced. Some views are applying complex logic, mostly due to filtering different types of assessment. Deferred to the future.
> Patient Store Support to Sort Assessment Logs by Date and Time

- web_registry/src/components/PatientDetail/MoodProgress.tsx
- web_registry/src/components/PatientDetail/ProgressInformation.tsx
- web_registry/src/stores/PatientStore.ts
- web_shared/sorting.ts
Utility functions for sorted mood logs.
Existing uses of the unsorted mood logs appear to have been correct.
Based on #497.
> Patient Store Support to Sort Mood Logs by Date and Time

- web_patient/src/components/Chrome/Login.tsx
- web_registry/src/components/chrome/Login.tsx
A message of "Username incorrect." has been displayed when the actual error is in the password.
Correct to an appropriately ambiguous "Username or password incorrect.".
This fix is only at the surface. There is a separate need to explore underlying Cognito errors.
> Provide Appropriately Ambiguous Username or Password Error Message

- web_registry/src/components/caseload/CaseloadTable.tsx
Applies a yellow highlight when there are 3 months of participation remaining.
Fixed #504.
Images captured on 5/22/2024 show:
More than 3 months of participation remaining:
Less than or equal to 3 months of participation remaining:
> Highlight Enrollment Date After 9 Months

- scope_shared/scope/enums.py
- scope_shared/scope/schemas/utils/enums.json
- server_flask/enums.py
- web_registry/src/components/PatientDetail/PatientProfileDialog.tsx
- web_registry/src/components/caseload/CaseloadTable.tsx
- web_shared/enums.ts
- web_shared/time.ts
By request, highlight any "Follow-Up Due" in caseload overview which is overdue.
- A follow-up is overdue and highlighted in yellow whenever the displayed follow-up due date is in the past.
- A new "As needed" follow-up schedule has been introduced. If selected, no follow-up due date is calculated.
- When treatment status is changed to "D/C", follow-up schedule automatically changes to "As Needed".
> Highlight Overdue Follow-Up, Add "As Needed" Follow-Up Schedule

- web_registry/src/components/caseload/CaseloadTable.tsx
In the caseload overview, the yellow highlight of Follow-Up Due should not be applied until 1 month overdue.
> Follow-Up Due Should Highlight After 1 Month

- web_registry/src/components/PatientDetail/PatientDetailPage.tsx
- web_registry/src/components/common/ContentsMenu.tsx
Provides an initial indication of the cutoff being used to define recent patient entry:
| ![Screenshot 2024-07-28 at 09-04-38 SCOPE Registry](https://github.com/user-attachments/assets/5e860949-6c0b-4f01-a74f-1ca31f681698) | ![Screenshot 2024-07-28 at 08-32-06 SCOPE Registry](https://github.com/user-attachments/assets/2d1bc39f-f9cf-4513-af17-eecef4dae710) |
This lays groundwork for being able to mark new entries as reviewed, with a proposed design:
| Proposed |
| ----- |
| ![Screenshot 2024-07-28 at 08-28-36 SCOPE Registry](https://github.com/user-attachments/assets/a2484684-c80e-46b9-923e-38eda5588eac) |
> Registry Indicator for Patient Recent Entry Cutoff

- web_registry/src/components/PatientDetail/PatientDetailPage.tsx
- web_registry/src/components/common/ContentsMenu.tsx
- web_registry/src/stores/PatientStore.ts
This improves upon and replaces the design that was in:
- #526
| With Recent Entry | Without Recent Entry |
| ![Screenshot 2024-07-29 at 18-45-18 SCOPE Registry](https://github.com/user-attachments/assets/3a56e93e-abc5-48f5-99a3-99139087fbe5) | ![Screenshot 2024-07-29 at 18-45-41 SCOPE Registry](https://github.com/user-attachments/assets/dd957e2c-d5b3-47dd-88b8-d3aba35fc6c3) |
Also includes updates for proposed designs:
| Proposed With Recent Entry | Proposed Without Recent Entry |
| ![Screenshot 2024-07-29 at 18-51-22 SCOPE Registry](https://github.com/user-attachments/assets/b2fec0e8-3d6e-4603-9ff1-22628d2fbc20) | ![Screenshot 2024-07-29 at 18-52-49 SCOPE Registry](https://github.com/user-attachments/assets/125f3ae3-55ad-442d-9bc0-9e563011c29b) |
> Updated Registry Indicator for Patient Recent Entry Cutoff

- web_registry/src/stores/PatientStore.ts
Assessments entered by a provider on behalf of a patient are not considered a recent entry and therefore "new".
The original implementation considered all assessments as potentially "new". This updates the patient store's calculation of `recentEntryAssessmentLogsSortedByDateAndTimeDescending` to filter on the presence of `submittedByProviderId`.
> Remove Provider-Submitted Assessments from Recent Patient Activity Indicators

- web_registry/src/components/common/ContentsMenu.tsx
- web_registry/src/stores/PatientStore.ts
- web_shared/guards.ts
When the definition of recent entry was based only on the current date/time, it was never undefined.
When it is based on stored documents, we need to allow/support that it may be undefined.
This is a step toward calculating the cutoff from marks, from a patient's enrollment date, or it being undefined.
> Allow Recent Entry Cutoff to be Undefined

- web_registry/src/components/PatientDetail/SessionInfo.tsx
Fixes a bug where the registry visualization of assessments was not using the sorted assessments:
| Before |
| ----- |
| ![353204054-0352d271-b025-4dbf-b737-3dc73e5dc038](https://github.com/user-attachments/assets/700e2726-4a18-4cb9-b3ee-1d2440c26dd0) |
| After |
| ----- |
| ![image](https://github.com/user-attachments/assets/3940018e-7a54-4123-a832-b31e7e928474) |
Fixes #289, which has more history on the bug.
> Fix Chronological Sort of Assessments in Registry Session Table Visualization 

- scope_shared/scope/database/patients.py
- scope_shared/scope/populate/patient/rule_populate_default_data.py
- scope_shared/scope/schemas/documents/review-mark.json
- scope_shared/scope/testing/fake_data/fixtures_fake_review_mark.py
- web_shared/types.ts
Newly-created patients will be created with an empty `reviewMark`. This ensures that new patients will initially show any data since enrollment as "new". We decided upon this after the deployment of v0.18.0.
Fixes #537, except we took a different approach than was initially sketched there. We included this in `ensure_patient_documents` (i.e., rather than in a populate script) so it would automatically happen if patient creation later moves out of populate scripts (e.g., in a self-deployed version of this).
#540 documents an ongoing need to be sensitive to this change in any future data migration.
>  Create an Empty Recent Entry Mark for Newly-Created Patients

- scope_shared/scope/database/patient/activity_schedules.py
- scope_shared/scope/database/patient/assessments.py
Based on realization this was still set to 3 months, update to 9 months (i.e., end of study period).
> Extend Scheduled Items Length to 9 Months
